import {  NextResponse } from 'next/server'


export function GET() {
    return NextResponse.json([
        { name: "Trenton modular sofa 3", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["sofa","trenton"], width: 283, height: 283, image: "/Trenton modular sofa_3 1.png", rating: 4.5, stockQuantity: 50, id: 1, discountPercentage: 8, isFeaturedProduct: true, catogory: "Sofa",},
        { name: "Granite dining table with dining chair", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Granite","dining","table"], width: 283, height: 283, image: "/Granite dining table with dining chair 1.png", rating: 4.5, stockQuantity: 50, id: 2, discountPercentage: 12, isFeaturedProduct: true, catogory: "Chair",},
        { name: "Outdoor bar table and stool", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["table","Outdoor","stool"], width: 283, height: 283, image: "/Outdoor bar table and stool 1.png", rating: 4.5, stockQuantity: 50, id: 3, discountPercentage: 18, isFeaturedProduct: true, catogory: "Table",},
        { name: "Plain console with teak mirror", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Plain console","teak mirror"], width: 283, height: 283, image: "/Plain console with teak mirror 1.png", rating: 4.5, stockQuantity: 50, id: 4, discountPercentage: 4, isFeaturedProduct: true, catogory: "Chair",},
        { name: "Grain coffee table", price: 258200.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Grain", "coffee","table"], width: 283, height: 283, image: "/Grain coffee table 1.png", rating: 4.5, stockQuantity: 50, id: 5, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Kent coffee table", price: 20000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Kent","coffee", "table"], width: 283, height: 283, image: "/Kent coffee table 1.png", rating: 4.5, stockQuantity: 50, id: 6, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Round coffee table_color 2", price: 200000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Round","table","coffee"], width: 283, height: 283, image: "/Round coffee table_color 2 1.png", rating: 4.5, stockQuantity: 50, id: 7, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Reclaimed teak coffee table", price: 100000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Reclaimed teak","table", "coffee"], width: 283, height: 283, image: "/Reclaimed teak coffee table 1.png", rating: 4.5, stockQuantity: 50, id: 8, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Plain console_", price: 258200.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Plain","console_"], width: 283, height: 283, image: "/Plain console_ 1.png",  rating: 4.5, stockQuantity: 50, id: 9, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Reclaimed teak Sideboard", price: 20000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Reclaimed teak","Sideboard"], width: 283, height: 283, image: "/Reclaimed teak Sideboard 1.png",  rating: 4.5, stockQuantity: 50, id: 10, discountPercentage: 0, isFeaturedProduct: false, catogory: "SideBoard", },
        { name: "SJP_0825 ", price: 200000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["SJP","sofa"], width: 283, height: 283, image: "/SJP_0825  1.png",  rating: 4.5, stockQuantity: 50, id: 11, discountPercentage: 0, isFeaturedProduct: false,  catogory: "Chair",},
        { name: "Bella chair and table", price: 100000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Bella","table", "chair"], width: 283, height: 283, image: "/Bella chair and table 1.png",  rating: 4.5, stockQuantity: 50, id: 12, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table", },
        { name: "Granite square side table", price: 258800.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Granite","side table", "square"], width: 283, height: 283, image: "/Granite square side table 2.png",  rating: 4.5, stockQuantity: 50, id: 13, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table", },
        { name: "Asgaard sofa", price: 250000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Asgaard","sofa"], width: 283, height: 283, image: "/Asgaard sofa 2.png",  rating: 4.5, stockQuantity: 50, id: 14, discountPercentage: 0, isFeaturedProduct: false, catogory: "Sofa", },
        { name: "Maya sofa three seater", price: 115000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["sofa","Maya", "three seater"], width: 283, height: 283, image: "/Maya sofa three seater 1.png",  rating: 4.5, stockQuantity: 50, id: 15, discountPercentage: 0, isFeaturedProduct: false, catogory: "Sofa", },
        { name: "Outdoor sofa set", price: 244000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["sofa","Outdoor set"], width: 283, height: 283, image: "/Outdoor sofa set 1.png",  rating: 4.5, stockQuantity: 50, id: 16, discountPercentage: 0, isFeaturedProduct: false, catogory: "Sofa", },
        { name: "Trenton modular sofa 3", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["sofa","trenton"], width: 283, height: 283, image: "/Trenton modular sofa_3 1.png", rating: 4.5, stockQuantity: 50, id: 17, discountPercentage: 8, isFeaturedProduct: true, catogory: "Sofa",},
        { name: "Granite dining table with dining chair", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Granite","dining","table"], width: 283, height: 283, image: "/Granite dining table with dining chair 1.png", rating: 4.5, stockQuantity: 50, id: 18, discountPercentage: 12, isFeaturedProduct: true, catogory: "Chair",},
        { name: "Outdoor bar table and stool", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["table","Outdoor","stool"], width: 283, height: 283, image: "/Outdoor bar table and stool 1.png", rating: 4.5, stockQuantity: 50, id: 19, discountPercentage: 18, isFeaturedProduct: true, catogory: "Table",},
        { name: "Plain console with teak mirror", price: 25000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Plain console","teak mirror"], width: 283, height: 283, image: "/Plain console with teak mirror 1.png", rating: 4.5, stockQuantity: 50, id: 20, discountPercentage: 4, isFeaturedProduct: true, catogory: "Chair",},
        { name: "Grain coffee table", price: 258200.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Grain", "coffee","table"], width: 283, height: 283, image: "/Grain coffee table 1.png", rating: 4.5, stockQuantity: 50, id: 21, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Kent coffee table", price: 20000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Kent","coffee", "table"], width: 283, height: 283, image: "/Kent coffee table 1.png", rating: 4.5, stockQuantity: 50, id: 22, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Round coffee table_color 2", price: 200000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Round","table","coffee"], width: 283, height: 283, image: "/Round coffee table_color 2 1.png", rating: 4.5, stockQuantity: 50, id: 23, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Reclaimed teak coffee table", price: 100000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Reclaimed teak","table", "coffee"], width: 283, height: 283, image: "/Reclaimed teak coffee table 1.png", rating: 4.5, stockQuantity: 50, id: 24, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Plain console_", price: 258200.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Plain","console_"], width: 283, height: 283, image: "/Plain console_ 1.png",  rating: 4.5, stockQuantity: 50, id: 25, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table",},
        { name: "Reclaimed teak Sideboard", price: 20000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Reclaimed teak","Sideboard"], width: 283, height: 283, image: "/Reclaimed teak Sideboard 1.png",  rating: 4.5, stockQuantity: 50, id: 26, discountPercentage: 0, isFeaturedProduct: false, catogory: "SideBoard", },
        { name: "SJP_0825 ", price: 200000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["SJP","sofa"], width: 283, height: 283, image: "/SJP_0825  1.png",  rating: 4.5, stockQuantity: 50, id: 27, discountPercentage: 0, isFeaturedProduct: false,  catogory: "Chair",},
        { name: "Bella chair and table", price: 100000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Bella","table", "chair"], width: 283, height: 283, image: "/Bella chair and table 1.png",  rating: 4.5, stockQuantity: 50, id: 28, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table", },
        { name: "Granite square side table", price: 258800.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Granite","side table", "square"], width: 283, height: 283, image: "/Granite square side table 2.png",  rating: 4.5, stockQuantity: 50, id: 29, discountPercentage: 0, isFeaturedProduct: false, catogory: "Table", },
        { name: "Asgaard sofa", price: 250000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["Asgaard","sofa"], width: 283, height: 283, image: "/Asgaard sofa 2.png",  rating: 4.5, stockQuantity: 50, id: 30, discountPercentage: 0, isFeaturedProduct: false, catogory: "Sofa", },
        { name: "Maya sofa three seater", price: 115000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["sofa","Maya", "three seater"], width: 283, height: 283, image: "/Maya sofa three seater 1.png",  rating: 4.5, stockQuantity: 50, id: 31, discountPercentage: 0, isFeaturedProduct: false, catogory: "Sofa", },
        { name: "Outdoor sofa set", price: 244000.00, description: "Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound.", tags: ["sofa","Outdoor set"], width: 283, height: 283, image: "/Outdoor sofa set 1.png",  rating: 4.5, stockQuantity: 50, id: 32, discountPercentage: 0, isFeaturedProduct: false, catogory: "Sofa", }
    ])
}

